config/routes.rb
Collages::Application.routes.draw do

  
resources :colleges, :only => [:index,:show]

     namespace :admin do
     resources :states
     resources :cities
     resources :categories
     resources :stream_categories
     resources :colleges
     resources :college_streams

    match '/add-cources', to: 'college_streams#find_cources',     via: 'post'
    match '/get-cities', to: 'colleges#find_cities',     via: 'post'

     end
end

app/models/stream_category.rb
class StreamCategory < ActiveRecord::Base
  belongs_to:category
  has_many:college_streams
end

app/controllers/admin/stream_categories_controller.rb
class Admin::StreamCategoriesController < ApplicationController
  before_action :set_stream_category, only: [:show, :edit, :update, :destroy]

  # GET /stream_categories
  # GET /stream_categories.json
  def index
    @stream_categories = searchitems(params[:search],StreamCategory,'name')
  end

  # GET /stream_categories/1
  # GET /stream_categories/1.json
  def show
  end

  # GET /stream_categories/new
  def new
    @stream_category = StreamCategory.new
  end

  # GET /stream_categories/1/edit
  def edit
  end

  # POST /stream_categories
  # POST /stream_categories.json
  def create
    @category = Category.find(params[:stream_category][:id])
    @stream_category = @category.stream_categories.create(stream_category_params)

    respond_to do |format|
      if @stream_category.save
        format.html { redirect_to admin_stream_category_path(@stream_category), notice: 'Stream category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stream_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @stream_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stream_categories/1
  # PATCH/PUT /stream_categories/1.json
  def update
    respond_to do |format|
      if @stream_category.update(stream_category_params)
        format.html { redirect_to admin_stream_category_path(@stream_category), notice: 'Stream category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stream_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stream_categories/1
  # DELETE /stream_categories/1.json
  def destroy
    @stream_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_stream_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream_category
      @stream_category = StreamCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_category_params
      params.require(:stream_category).permit(:name,:stream_category_id)
    end
end

app/helpers/stream_categories_helper.rb
module StreamCategoriesHelper
end

app/views/admin/stream_categories/_form.html.erb
<div class="column c-67 clearfix">
  <div class="box contactUs ">
    <h4><span>New Course</span></h4>
    <div class="boxInfo contactForm">
<%= form_for [:admin,@stream_category] do |f| %>
  <% if @stream_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stream_category.errors.count, "error") %> prohibited this stream_category from being saved:</h2>

      <ul>
      <% @stream_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
      <div class="field">
    <%= f.label :category_id %>
    <%= collection_select(:stream_category, :id, Category.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit "Create",:class => 'submit' %>
  </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/stream_categories/edit.html.erb
<h1>Editing stream_category</h1>

<%= render 'form' %>

<%= link_to 'Show', stream_category_path(@stream_category) %> |
<%= link_to 'Back', admin_stream_categories_path %>

app/views/admin/stream_categories/index.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p>Stream<strong> List</strong></p>
    </div>

    <div class="wrapper">

      <div class="course column c-67 clearfix">
        <table class="box">
          <tr class="tableHeader">
      <th>Stream Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @stream_categories.each do |stream_category| %>
      <tr>
        <td><%= stream_category.name %></td>
        <td><%= link_to 'Show', admin_stream_category_path(stream_category) %></td>
        <td><%= link_to 'Edit', edit_admin_stream_category_path(stream_category) %></td>
        <td><%= link_to 'Destroy', '#', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
        <%= will_paginate @states,:id =>'photopagination' %>
      </div>

      <div id="sidebar" class="column c-33 clearfix">

        <div class="clearfix">
          <div class="box">
            <h4>Search: <strong>stream</strong></h4>
            <div class="boxInfo">
              <%= form_tag admin_stream_categories_path, :method => 'get' do %>  

        <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Go", :name => nil,:id =>'mailSubmit' %>  
      <% end %> 
            </div>
          </div>
        </div>


      </div> 

    </div>

  </div>
</div>

app/views/admin/stream_categories/new.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p><strong>Streams</strong></p>
      <%= controller_path.split('/').first %>
    </div>

    <div class="wrapper">

<%= render 'form' %>

    </div>
  </div>
</div>

app/views/admin/stream_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stream_category.name %>
</p>

<%= link_to 'Edit', edit_admin_stream_category_path(@stream_category) %> |
<%= link_to 'Back', admin_stream_categories_path %>