config/routes.rb
Collages::Application.routes.draw do

  
resources :colleges, :only => [:index,:show]

     namespace :admin do
     resources :states
     resources :cities
     resources :categories
     resources :stream_categories
     resources :colleges
     resources :college_streams

    match '/add-cources', to: 'college_streams#find_cources',     via: 'post'
    match '/get-cities', to: 'colleges#find_cities',     via: 'post'

     end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many:stream_categories
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = searchitems(params[:search],Category,'name')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
  
  def find_cources
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="column c-67 clearfix">
  <div class="box contactUs ">
    <h4><span>New Course</span></h4>
    <div class="boxInfo contactForm">
<%= form_for [:admin,@category] do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Create",:class => 'submit' %>
  </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p>Course<strong> List</strong></p>
    </div>

    <div class="wrapper">

      <div class="course column c-67 clearfix">
        <table class="box">
          <tr class="tableHeader">
      <th>Course Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', admin_category_path(category) %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', '#', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
        <%= will_paginate @states,:id =>'photopagination' %>
      </div>

      <div id="sidebar" class="column c-33 clearfix">

        <div class="clearfix">
          <div class="box">
            <h4>Search: <strong>Course</strong></h4>
            <div class="boxInfo">
              <%= form_tag admin_categories_path, :method => 'get' do %>  

        <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Go", :name => nil,:id =>'mailSubmit' %>  
      <% end %> 
            </div>
          </div>
        </div>


      </div> 

    </div>

  </div>
</div>

app/views/admin/categories/new.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p>Our <strong>Courses</strong></p>
    </div>

    <div class="wrapper">

<%= render 'form' %>

    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>