config/routes.rb
Collages::Application.routes.draw do

  
resources :colleges, :only => [:index,:show]

     namespace :admin do
     resources :states
     resources :cities
     resources :categories
     resources :stream_categories
     resources :colleges
     resources :college_streams

    match '/add-cources', to: 'college_streams#find_cources',     via: 'post'
    match '/get-cities', to: 'colleges#find_cities',     via: 'post'

     end
end

app/models/college.rb
class College < ActiveRecord::Base
  belongs_to:city
  belongs_to:state
  validates :name, presence: true, uniqueness: true
  validates :information, presence: true
  validates :year, presence: true
  validates :address1, presence: true
  validates :address2, presence: true
  validates :state_id, presence: true
  validates :city_id, presence: true
  validates :pincode, presence: true
  validates :collage_type, presence: true
  validates :college_website, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :college_email, presence:   true,
    format:     { with: VALID_EMAIL_REGEX }
# validates :phone, presence: true, length: { maximum: 10 }
# validates :information, presence: true, length: { maximum: 500 }
end

app/controllers/admin/colleges_controller.rb
class Admin::CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    
    @colleges = searchitems(params[:search],College,'name')
    
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
    @states = State.all
    @cities = City.all
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)
    #raise params[:state_id]
    if @college.save
      redirect_to new_admin_college_stream_path(:episode => @college.id) 
      #format.html { redirect_to admin_college_path(@college), notice: 'College was successfully created.' }
      #format.json { render action: 'show', status: :created, location: @college }
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    
    if @college.update(college_params)
      format.html { redirect_to admin_college_path(@college), notice: 'College was successfully updated.' }
    else
      render action: 'edit' 
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end

  def find_cities
    @state_id = params[:state_id]
    @state = State.find(@state_id)
    @cities = @state.cities.all
    city = Hash.new
    @cities.each do |cource|
      city[cource.id] = cource.name 
    end
    
    render :json => city
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_college
    @college = College.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def college_params
    params.require(:college).permit(:name, :information, :year, :address1, :address2, :state_id , :city_id, :pincode, :landline, :mobile, :collage_type, :tution_fee, :college_website, :college_email, :facebook_link, :twitter_link, :linkedin_link)
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = searchitems(params[:search],College,'name')
  end
  
  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

   private
  # Use callbacks to share common setup or constraints between actions.
  def set_college
    @college = College.find(params[:id])
  end
  
end

app/helpers/colleges_helper.rb
module CollegesHelper
  
  def searchitems(search,model,searchby)
    if search  
      model.paginate( :conditions => [searchby +' LIKE ?', "%#{search}%"],:page => params[:page], :per_page => 10,:order => 'name')
    else  
      model.paginate(:page => params[:page], :per_page => 10,:order => 'name') 
    end  
  end
end

app/views/colleges/_form.html.erb
<script>
  
  $(document).ready(function () {
    var $el = $("#college_city_id");
    $el.prop("disabled", true);
  });
  $(function() {
  $(document).on('change', '#college_state_id', function() {
     var state_id = $('#college_state_id').val();
    if (state_id != '') {
      $.ajax({
        type: "post",
        url: "/admin/get-cities",
        data: {state_id: state_id},
        success: function(data) {
          var $el = $("#college_city_id");
          $el.empty(); // remove old options
          $.each(data, function(key, value) {
            $el.append($("<option></option>")
                    .attr("value", key).text(value));
          });
          $("#college_city_id").prop("disabled", false);
        }
      });
    }
    else {
      var $el = $("#college_city_id");
      $el.empty();
      $el.append($("<option></option>")
              .attr("value", '').text('Cities'));
      $el.prop("disabled", true);
    }
  });
});




</script>

<div class="column c-67 clearfix">
                        <div class="box contactUs ">
                            <h4><span>New Collage</span></h4>
                                <div class="boxInfo contactForm">
  <%= form_for [:admin,@college] do |f| %>
    <% if @college.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

        <ul>
          <% @college.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :information %>
      <%= f.text_area :information %>
    </div>
    <div class="field">
      <%= f.label :year %>
      <%= f.text_field :year,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :address1 %>
      <%= f.text_field :address1,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :address2 %>
      <%= f.text_field :address2,:id => 'contactName' %>
    </div>
    <div class="field" id="test">
      <%= f.label :state_id %>
      <%=  f.select "state_id",options_from_collection_for_select(State.all, "id", "name"),:class => 'select-style',:prompt => "State",:onchange => "get_cities(this.value)"%>
    </div>
    <div class="field">
      <%= f.label :city_id %>
      <%=  f.select "city_id",options_from_collection_for_select(City.all, "id", "name"),:class => 'select-style',:prompt => "City",:disabled => true%>
    </div>
    <div class="field">
      <%= f.label :pincode %>
      <%= f.text_field :pincode,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :landline %>
      <%= f.text_field :landline,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :mobile %>
      <%= f.text_field :mobile,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :collage_type %>
      <%= f.number_field :collage_type,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :tution_fee %>
      <%= f.text_field :tution_fee,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :college_website %>
      <%= f.text_field :college_website,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :college_email %>
      <%= f.text_field :college_email,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :facebook_link %>
      <%= f.text_field :facebook_link,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :twitter_link %>
      <%= f.text_field :twitter_link,:id => 'contactName' %>
    </div>
    <div class="field">
      <%= f.label :linkedin_link %>
      <%= f.text_field :linkedin_link,:id => 'contactName' %>
    </div>
    <div class="actions">
      <%= f.submit "Create",:class => 'submit' %>
    </div>
  <% end %>
</div>
                        </div>
</div>

app/views/colleges/edit.html.erb
<h1>Editing college</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_college_path(@college) %> |
<%= link_to 'Back', admin_colleges_path %>

app/views/colleges/index.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p>Our <strong>Course</strong></p>
    </div>

    <div class="wrapper">

      <div class="course column c-67 clearfix">
        <h3 class="title">Collage <strong>List</strong></h3>
            <% @colleges.each do |college| %>
            <div class="box">
                            <ul class="courseId">
                                <li><%=  college.name %></li>
                                <li>Collage Type: <%=  college.collage_type %></li>
                            </ul>
                            <div class="boxInfo">
                                <p><%= truncate college.information, length: 150 %></p>
                            </div>
                            <div class="courseInfo">
                                <p class="courseTime">Year of Establishment: <%= college.year %></p>
                                <ul>
                                    <li class="courseRoom">Website: <%= link_to  college.college_website, 'http://' + college.college_website,:target => '_blank' %></li>
                                    
                                </ul>
                            </div>
                        </div>
        <% end %>
          
            
      </div>

      <div id="sidebar" class="column c-33 clearfix">

        <div class="clearfix">
          <div class="box">
            <h4>Search: <strong>Collage</strong></h4>
            <div class="boxInfo">
              <%= form_tag colleges_path, :method => 'get' do %>  

        <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Go", :name => nil,:id =>'mailSubmit' %>  
      <% end %> 
            </div>
          </div>
        </div>


      </div> 

    </div>

  </div>
</div>

<!-- FOOTER -->

app/views/colleges/new.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p><strong>Collages</strong></p>
    </div>

    <div class="wrapper">

<%= render 'form' %>

    </div>
  </div>
</div>

<%= link_to 'Back', admin_colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @college.information %>
</p>

<p>
  <strong>Year:</strong>
  <%= @college.year %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @college.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @college.address2 %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @college.pincode %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @college.landline %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @college.mobile %>
</p>

<p>
  <strong>Collage type:</strong>
  <%= @college.collage_type %>
</p>

<p>
  <strong>Tution fee:</strong>
  <%= @college.tution_fee %>
</p>

<p>
  <strong>College website:</strong>
  <%= @college.college_website %>
</p>

<p>
  <strong>College email:</strong>
  <%= @college.college_email %>
</p>

<p>
  <strong>Facebook link:</strong>
  <%= @college.facebook_link %>
</p>

<p>
  <strong>Twitter link:</strong>
  <%= @college.twitter_link %>
</p>

<p>
  <strong>Linkedin link:</strong>
  <%= @college.linkedin_link %>
</p>

<%= link_to 'Back', admin_colleges_path %>