config/routes.rb
Collages::Application.routes.draw do

  
resources :colleges, :only => [:index,:show]

     namespace :admin do
     resources :states
     resources :cities
     resources :categories
     resources :stream_categories
     resources :colleges
     resources :college_streams

    match '/add-cources', to: 'college_streams#find_cources',     via: 'post'
    match '/get-cities', to: 'colleges#find_cities',     via: 'post'

     end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many:cities, dependent: :destroy
  has_many:colleges
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = searchitems(params[:search],State,'name')
    #@states = State.order(:name)
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to admin_state_path(@state), notice: 'State was successfully created.' }
        format.json { render action: 'show', status: :created, location: @state }
      else
        format.html { render action: 'new' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to admin_state_path(@state), notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to admin_states_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/admin/states/_form.html.erb
<div class="column c-67 clearfix">
  <div class="box contactUs ">
    <h4><span>New State</span></h4>
    <div class="boxInfo contactForm">
      <%= form_for [:admin,@state] do |f| %>
        <% if @state.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

            <ul>
              <% @state.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="actions">
          <%= f.submit "Create",:class => 'submit' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_state_path(@state) %> |
<%= link_to 'Back', admin_states_path %>

app/views/admin/states/index.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p>State<strong> List</strong></p>
    </div>

    <div class="wrapper">

      <div class="course column c-67 clearfix">
        <table class="box">
          <tr class="tableHeader">
      <th>State Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show',admin_state_path(state) %></td>
        <td><%= link_to 'Edit', edit_admin_state_path(state) %></td>
        <td><%= link_to 'Destroy', '#', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
        <%= will_paginate @states,:id =>'photopagination' %>
      </div>

      <div id="sidebar" class="column c-33 clearfix">

        <div class="clearfix">
          <div class="box">
            <h4>Search: <strong>State</strong></h4>
            <div class="boxInfo">
              <%= form_tag admin_states_path, :method => 'get' do %>  

        <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Go", :name => nil,:id =>'mailSubmit' %>  
      <% end %> 
            </div>
          </div>
        </div>


      </div> 

    </div>

  </div>
</div>

<!-- FOOTER -->

app/views/admin/states/new.html.erb
<div id="contentBk" class="clearfix">

  <div id="content">
    <div class="topImg clearfix">
      <img src="/assets/headers/header_2.jpg" alt="About Us">
      <p><strong>States</strong></p>
    </div>

    <div class="wrapper">

<%= render 'form' %>

    </div>
  </div>
</div>

app/views/admin/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_admin_state_path(@state) %> |
<%= link_to 'Back', admin_states_path %>